### ISSUE TITLE
本地启动找不到包

### ISSUE THREAD

**Issue by CodeFarmerier** [buqiyuan/nest-admin#48]
#### Steps to reproduce（问题复现步骤）
1. 使用pnpm dev的时候 报错 
2. 我根据报错路径去查找，发现是有这个文件，但是运行的时候没有build进去
3. 以下是报错信息
Error: Cannot find module '/Users/后端/node项目/nest-admin/src/common/dto/pager.dto'
Require stack:
- /Users/后端/node项目/nest-admin/dist/common/dto/pager.dto.js
- /Users/后端/node项目/nest-admin/dist/modules/system/role/role.controller.js
- /Users/后端/node项目/nest-admin/dist/modules/system/role/role.module.js
- /Users/后端/node项目/nest-admin/dist/modules/system/menu/menu.module.js
- /Users/后端/node项目/nest-admin/dist/modules/user/user.module.js
- /Users/后端/node项目/nest-admin/dist/modules/system/log/log.module.js
- /Users/后端/node项目/nest-admin/dist/modules/auth/auth.module.js
- /Users/后端/node项目/nest-admin/dist/app.module.js
- /Users/后端/node项目/nest-admin/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Function._OPENAPI_METADATA_FACTORY (/Users/后端/node项目/nest-admin/dist/common/dto/pager.dto.js:29:234)
    at /Users/后端/node项目/nest-admin/node_modules/.pnpm/@nestjs+swagger@7.3.1_@fastify+static@7.0.3_@nestjs+common@10.3.7_@nestjs+core@10.3.7_class-t_rc635vf3pb3uuk3dyc4mkw3f7a/node_modules/@nestjs/swagger/dist/decorators/helpers.js:48:241
    at DecorateProperty (/Users/后端/node项目/nest-admin/node_modules/.pnpm/reflect-metadata@0.2.2/node_modules/reflect-metadata/Reflect.js:561:33)
    at Reflect.decorate (/Users/后端/node项目/nest-admin/node_modules/.pnpm/reflect-metadata@0.2.2/node_modules/reflect-metadata/Reflect.js:136:24)
    at __decorate (/Users/后端/node项目/nest-admin/dist/common/dto/pager.dto.js:4:92)
    at Object.<anonymous> (/Users/后端/node项目/nest-admin/src/common/dto/pager.dto.ts:19:3)

#### Screenshot or Gif（截图或动态图）
![Snipaste_2024-05-09_22-30-57](https://github.com/buqiyuan/nest-admin/assets/168082438/de43e11e-2362-41d2-9e51-08843eaa0be2)

#### Other relevant information（格外信息）
- Your OS: macos
- Node.js version: v18.18.0
- Mysql version: 8.3
- Redis version: 7.2.4
- pnpm version:8.10.2

**Comment by CodeFarmerier** [comment]
![Snipaste_2024-05-09_22-41-11](https://github.com/buqiyuan/nest-admin/assets/168082438/2c160ca6-0911-4aad-a6f1-10b1763336cf)
dist目录中有这歌文件

**Comment by zjincHub** [comment]
找到解决方法了吗，我也遇到这个问题了

**Comment by zjincHub** [comment]
找到问题了，路径不能包含中文哈

**Comment by tymoony** [comment]
确实是中文路径的问题
