### ISSUE TITLE
按照文档启动就报错。接口文档也打不开

### ISSUE THREAD

**Issue by Fluox-Etine** [buqiyuan/nest-admin#72]
9:49:59] Starting compilation in watch mode...

[19:50:12] Found 0 errors. Watching for file changes.

node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'C:/Users/jack/Desktop/develop/参考代码/admin/node/nest-admin/src/common/dto/pager.dto'
Require stack:
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\common\dto\pager.dto.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\system\role\role.dto.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\system\role\role.controller.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\system\role\role.module.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\system\menu\menu.module.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\user\user.module.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\system\log\log.module.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\modules\auth\auth.module.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\app.module.js
- C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\main.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Function._OPENAPI_METADATA_FACTORY (C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\src\common\dto\pager.dto.ts:44:14)
    at C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\node_modules\.pnpm\@nestjs+swagger@7.4.2_@fastify+static@7.0.4_@nestjs+common@10.4.4_class-transformer@0.5.1_cla_prq3gmmavv2r2ghuxupvqwwwbe\node_modules\@nestjs\swagger\dist\decorators\helpers.js:48:241
    at DecorateProperty (C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\node_modules\.pnpm\reflect-metadata@0.2.2\node_modules\reflect-metadata\Reflect.js:561:33)
    at Reflect.decorate (C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\node_modules\.pnpm\reflect-metadata@0.2.2\node_modules\reflect-metadata\Reflect.js:136:24)
    at __decorate (C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\dist\common\dto\pager.dto.js:4:92)
    at Object.<anonymous> (C:\Users\jack\Desktop\develop\参考代码\admin\node\nest-admin\src\common\dto\pager.dto.ts:19:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\common\\dto\\pager.dto.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\system\\role\\role.dto.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\system\\role\\role.controller.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\system\\role\\role.module.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\system\\menu\\menu.module.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\user\\user.module.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\system\\log\\log.module.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\modules\\auth\\auth.module.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\app.module.js',
    'C:\\Users\\jack\\Desktop\\develop\\参考代码\\admin\\node\\nest-admin\\dist\\main.js'
  ]
}

**Comment by choecode** [comment]
+1
